



export const INITIAL_INFLUENCERS = 'INITIAL_INFLUENCERS';
export const NEXT_INFLUENCERS = 'NEXT_INFLUENCERS';
export const PREVIOUS_INFLUENCERS = 'PREVIOUS_INFLUENCERS';
export const GET_INFLUENCERS = 'GET_INFLUENCERS';
export const ABORT = 'ABORT';
export const ERROR = 'ERROR';
